1:
  damage_percentage: 4
2:
  damage_percentage: 8
3:
  damage_percentage: 12
4:
  damage_percentage: 16
5:
  damage_percentage: 20
6:
  damage_percentage: 24
7:
  damage_percentage: 32
8:
  damage_percentage: 40
9:
  damage_percentage: 48
10:
  damage_percentage: 56
11:
  damage_percentage: 64
12:
  damage_percentage: 72
13:
  damage_percentage: 80
14:
  damage_percentage: 90
15:
  damage_percentage: 100
16:
  damage_percentage: 110
17:
  damage_percentage: 120
18:
  damage_percentage: 140
19:
  damage_percentage: 170
20:
  damage_percentage: 200
