1:
  armor_percentage: 4
2:
  armor_percentage: 6
3:
  armor_percentage: 8
4:
  armor_percentage: 10
5:
  armor_percentage: 12
6:
  armor_percentage: 14
7:
  armor_percentage: 18
8:
  armor_percentage: 22
9:
  armor_percentage: 26
10:
  armor_percentage: 30
11:
  armor_percentage: 34
12:
  armor_percentage: 38
13:
  armor_percentage: 44
14:
  armor_percentage: 50
15:
  armor_percentage: 56
16:
  armor_percentage: 62
17:
  armor_percentage: 70
18:
  armor_percentage: 78
19:
  armor_percentage: 88
20:
  armor_percentage: 100
