name: rk_friedloxmeat
clonePrefabName: 
craftingStation: Grill
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LoxMeat:1:0:False
- BarleyFlour:1:0:False
- mc_rawegg:1:0:False
- rk_butter:1:0:False
