name: rk_pancake
clonePrefabName: 
craftingStation: Grill
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Honey:2:0:False
- BarleyFlour:3:0:False
- rk_butter:4:0:False
- mc_rawegg:2:0:False
