name: BakedMagmaFishUncooked
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Fish11:1:0:True
- Dandelion:5:0:True
- Thistle:5:0:True
- RoyalJelly:10:0:True
