name: riceEggMeat
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- garlic:1:0:False
- rk_pork:1:0:False
- rice:2:0:False
- mc_rawegg:1:0:False
