name: mc_boiledegg
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- mc_rawegg:1:0:True
