name: rk_fishstew
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- rk_broth:2:0:False
- FishRaw:2:0:False
- Thistle:2:0:False
- mc_rawegg:2:0:False
