name: MushroomOmelette
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- mc_rawegg:3:1:True
- MushroomJotunPuffs:3:1:True
