name: BakedSalmonUncooked
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Fish10:1:0:True
- MushroomMagecap:5:0:True
- Thistle:10:0:True
