name: rk_birthday
clonePrefabName: 
craftingStation: Grill
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BarleyFlour:2:0:False
- Honey:4:0:False
- Cloudberry:4:0:False
- mc_rawegg:2:0:False
