name: FishAndBreadUncooked
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Fish9:1:1:True
- BreadDough:2:1:True
