name: adventurers_breakfast
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RawMeat:1:0:False
- mc_rawegg:4:0:False
- Bread:1:0:False
