name: mc_chickencreamy
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- mc_rawchickenmeat:1:0:True
- mc_rawegg:1:0:True
- Carrot:2:0:True
- NeckTail:1:0:True
