name: FishBallUncooked
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Fish7:1:0:True
- BarleyFlour:5:0:True
- Dandelion:3:0:True
