name: MeatPlatterUncooked
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BugMeat:1:1:True
- LoxMeat:1:1:True
- HareMeat:1:1:True
