name: mc_chickenonionsoup
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- mc_rawchickenmeat:1:0:True
- mc_rawegg:1:0:True
- Onion:3:0:True
- Mushroom:1:0:True
