name: ramen_tonkotsu
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- raw_pasta:1:0:False
- rk_pork:1:0:False
- mc_rawegg:1:0:False
- Thistle:2:0:False
