name: mc_uncookedchickenpotpie
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- mc_rawchickenmeat:2:0:True
- mc_rawegg:2:0:True
- BarleyFlour:4:0:True
- Honey:3:0:True
