name: raw_pasta
clonePrefabName: 
craftingStation: Prep Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BarleyFlour:1:0:False
- salt:1:0:False
- mc_rawegg:2:0:False
