name: CupcakePlain_FF
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 6
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CupCakeBase_FF:6:0:False
- CornFlour_FF:3:0:False
- Butter_FF:2:0:False
- mc_rawegg:2:0:False
