name: mc_chickenturnip
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- mc_rawchickenmeat:1:0:True
- mc_rawegg:1:0:True
- Turnip:2:0:True
- Entrails:1:0:True
