label_almanac: 'Almanac'
label_only_in_biome: 'Only in biome'
label_crafting_station: 'Crafting station'
label_pieces: 'Pieces'
label_material_type: 'Material type'
label_supports: 'Supports'
label_false: 'False'
label_last_updated: 'Last updated'
label_true: 'True'
label_metrics: 'Metrics'
label_cancel: 'Cancel'
label_leaderboard: 'Leaderboard'
token_almanac: 'Almanac Token'
label_hunt: 'Hunt'
label_killed: 'Killed'
label_total_kills: 'Total kills'
label_chest_armor: 'Chest armor'
label_leg_armor: 'Leg armor'
label_customize: 'Customize'
label_total_deaths: 'Total deaths'
label_ratio: 'Ratio'
msg_bounty_available_in: 'Bounty available in'
msg_bountyescaped: 'Bounty escaped'
msg_bountystolen: 'Bounty stolen by'
label_bounties: 'Bounties'
label_treasures: 'Treasures'
msg_vanquished: 'Vanquished'
label_cancel_treasure: 'Cancel treasure hunt'
label_store: 'Store'
msg_treasure_available_in: 'Treasure available in'
label_search_for: 'Search for'
label_died: 'Died'
label_marketplace: 'Marketplace'
label_revenue: 'Revenue'
label_sell_item: 'Sell item'
label_sell_your_items: 'Sell your items'
label_inventory: 'Inventory'
label_character: 'Character'
label_drops: 'Drops'
label_added: 'Added'
label_apply_effect: 'Apply Effect'
label_removed: 'Removed'
label_remove_effect: 'Remove Effect'
label_collected: 'Collected'
label_picked: 'Picked'
label_collect: 'Collect'
label_reward: 'Reward'
label_in_progress: 'In progress'
label_progress: 'Progress'
label_close: 'Close'
label_biome: 'Biome'
label_cancel_bounty: 'Cancel bounty'
msg_bounty_canceled: 'Bounty has been canceled'
msg_treasure_canceled: 'Treasure has been canceled'
msg_failed_to_spawn_bounty: 'Failed to spawn bounty'
msg_returning_cost: 'Returning cost'
label_recipes: 'Recipes'
label_start_bounty: 'Start bounty'
label_loot: 'Loot'
label_cancel_hunt: 'Cancel hunt'
label_start_treasure_hunt: 'Start treasure hunt'
label_items: 'Items'
label_purchase: 'Purchase'
label_purchased: 'Purchased'
label_lottery: 'Lottery'
label_turret: 'Turret'
msg_too_many_achievements: 'Too many achievement effects active'
lore_lottery: 'Step up to the reels, warrior! Test your luck in a game of chance where your hard-earned spoils are on the line. Match enough symbols and you could walk away with riches beyond measure—or lose it all in the gods’ cruel jest. Risk it, and let fate decide!'
label_target_players: 'Target players'
label_target_tames: 'Target tames'
label_target_enemies: 'Target enemies'
label_chance: 'Chance'
label_gamble: 'Gamble'
placeholder_search: 'Search...'
msg_full_house: 'Full house !!'
msg_full_house_message: '{0} hit the jackpot for {1} tokens!'
label_chance_for_full_house: 'Chance for full house'
label_full_house_total: 'Full house Reward'
msg_cost: 'Cost'
label_setup_sale: 'Setup Sale'
label_cost_per_unit: 'Cost per unit'
label_success: 'Success !!'
msg_lottery_win: '{0} has won {1} tokens in the lottery!'
msg_fullhouse_win: '{0} just hit the jackpot and won {1} tokens!'
msg_try_again_next_time: 'Try again next time!!'
label_slots: 'Slots'
label_icons: 'Icons'
label_match_length: 'Match length'
label_possible_sequences: 'Possible Sequences'
label_chance_per_sequence: 'Chance per sequence'
label_per_matches: 'per matches'
label_expected_wins: 'Expected Wins'
label_win_chance: 'Win Chance'
label_failure_chance: 'Failure chance'
biome_none: 'None'
label_min: 'min'
label_lvl: 'lvl'
label_minutes: 'minutes'
label_xp: 'XP'
label_resistances: 'Resistances'
label_combat: 'Combat'
label_completed: 'Completed'
label_forsaken: 'Forsaken'
label_mortality: 'Mortality'
label_miscellaneous: 'Miscellaneous'
label_husbandry: 'Husbandry'
label_harvest: 'Harvest'
label_range: 'Range'
label_build: 'Build'
label_creature: 'Creature'
label_defense: 'Defense'
label_dungeon: 'Dungeon'
label_travel: 'Travel'
label_base: 'Base'
label_trees: 'Trees'
label_mining: 'Mining'
label_raven: 'Raven'
label_teleportable: 'Teleportable'
label_attack: 'Attack'
label_force: 'Force'
label_effect: 'Effect'
label_valuables: 'Valuables'
label_comfort: 'Comfort'
label_discover: 'Discover'
label_group: 'Group'
se_damagereduction: 'All'
label_grow: 'Grow'
label_life_steal: 'Life Steal'
label_new: 'New'
label_can_be_repaired: 'Can be repaired'
label_maxstacksize: 'Max stack size'
label_variant: 'Variant'
label_itemtype: 'Item Type'
label_questitem: 'Quest Item'
label_quest: 'Quest'
label_equipduration: 'Equip Duration'
label_floating: 'Floating'
label_fish: 'Fish'
label_swimrange: 'Swim Range'
label_mindepth: 'Min Depth'
label_speed: 'Speed'
label_acceleration: 'Acceleration'
label_turnrate: 'Turn Rate'
label_avoidrange: 'Avoid Range'
label_height: 'Height'
label_hookforce: 'Hook Force'
label_escapestaminause: 'Escape Stamina Use'
label_escape: 'Escape'
label_hook: 'Hook'
label_create: 'Create'
label_status_effect: 'Status Effect'
label_create_new_status_effect: 'Create new status effect'
label_require: 'Require'
label_required_defeated: 'Required Defeated'
label_roof: 'Roof'
label_jumponland: 'Jump on Land'
label_frequency: 'Frequency'
label_fast: 'Fast'
label_baits: 'Baits'
label_material: 'Material'
label_materials: 'Materials'
label_hide: 'Hide'
label_helmet: 'Helmet'
label_beard: 'Beard'
label_equipeffect: 'Equip Effect'
label_unique: 'Unique'
label_id: 'ID'
label_postedby: 'Posted by'
label_dateposted: 'Date Posted'
label_stat_modifier: 'Stat Modifier'
label_set: 'Set'
label_name: 'Name'
label_food: 'Food'
label_consumeeffect: 'Consume Effect'
label_prefab: 'PrefabID'
label_category: 'Category'
label_prefabname: 'Internal ID'
label_shield: 'Shield'
label_blockadrenaline: 'Block Adrenaline'
label_staves: 'Staves'
label_potions: 'Potions'
label_setname: 'Set Name'
label_weapon: 'Weapon'
label_cape: 'Cape'
label_sellyouritem: 'Sell your item'
label_almanactokenprice: 'Almanac token price'
label_stacksize: 'Stack size'
label_setsizeofstack: 'Set size of stack'
label_usedin: 'Used In'
label_animationstate: 'Animation State'
label_skilltype: 'Skill Type'
label_tooltier: 'Tool Tier'
label_dodgeable: 'Dodgeable'
label_blockable: 'Blockable'
label_trinkets: 'Trinkets'
label_alwaysrotate: 'Always Rotate'
label_spawnonhit: 'Spawn On Hit'
label_terrain: 'Terrain'
label_projectiletooltip: 'Projectile Tooltip'
label_ammo: 'Ammo'
label_type: 'Type'
label_animation: 'Animation'
label_random: 'Random'
label_rank: 'Rank'
label_chain: 'Chain'
label_looping: 'Looping'
label_hit: 'Hit'
label_ishomeitem: 'Is Home Item'
label_consume: 'Consume'
label_consumables: 'Consumables'
label_item: 'Item'
label_back: 'Back'
label_factor: 'Factor'
label_use: 'Use'
label_smelter: 'Smelter'
label_station_ext: 'Station Extension'
label_index: 'Index'
label_wearntear: 'Wear N Tear'
label_rotation: 'Rotation'
label_start: 'Start'
label_fuel: 'Fuel'
label_max: 'Max'
label_storage: 'Storage'
label_conversion: 'Conversion'
label_rate: 'Rate'
label_convert: 'Convert'
label_entry_dialogue_id: 'Entry Dialogue ID'
label_random_talk_id: 'Random Talk ID'
label_chest_item_id: 'Chest Item'
label_leg_item_id: 'Leg Item'
label_right_hand_item_id: 'Right Hand Item'
label_left_hand_item_id: 'Left Hand Item'
label_shoulder_item_id: 'Shoulder Item'
label_utility_item_id: 'Utility Item'
label_back_right_item_id: 'Back Right Item'
label_back_left_item_id: 'Back Left Item'
label_hair_item_id: 'Hair Item'
label_beard_item_id: 'Beard Item'
label_skin_color: 'Skin color'
label_hair_color: 'Hair color'
label_model_index: 'Model Index'
label_container: 'Container'
label_size: 'Size'
label_beehive: 'Bee Hive'
label_noise: 'Noise'
label_secondary: 'Secondary'
label_droppedby: 'Dropped By'
label_default: 'Default'
label_spawn: 'Spawn'
label_give: 'Give'
label_faction: 'Faction'
label_data: 'Data'
label_avoid: 'Avoid'
label_afraidof: 'Afraid of'
label_water: 'Water'
label_weakspots: 'Weakspot'
label_stagger: 'Stagger'
label_whenblockede: 'when blocked'
label_tolerate: 'Tolerate'
label_smoke: 'Smoke'
label_tar: 'Tar'
label_defeatkey: 'Defeat Key'
label_fed: 'Fed'
label_taming: 'Taming'
label_cookingstation: 'Cooking Station'
label_interval: 'Interval'
label_plant: 'Plant'
label_trap: 'Trap'
label_fireplace: 'Fireplace'
label_door: 'Door'
label_total: 'Total'
label_wispspawner: 'Wisp Spawner'
label_commandable: 'Commandable'
label_portal: 'Portal'
label_activationrange: 'Activation Range'
label_exitdistance: 'Exit Distance'
inventory_ignore: 'Ignore'
label_distance: 'Distance'
label_enabled: 'Enabled'
label_fermenter: 'Fermenter'
inventory_physical: 'Physical'
inventory_elemental: 'Elemental'
label_keyitem: 'Key Item'
label_piece: 'Piece'
label_extends: 'Extends'
label_overcooked: 'Over-Cooked'
label_amount: 'Amount'
label_threshold: 'Threshold'
label_achievement: 'Achievement'
label_target: 'Target'
label_incomingdamage: 'incoming damage'
inventory_normal: 'Normal'
playerstat_deaths: 'Deaths'
playerstat_craftsorupgrades: 'Crafts Or Upgrades'
playerstat_builds: 'Builds'
playerstat_jumps: 'Jumps'
playerstat_cheats: 'Cheats'
playerstat_enemyhits: 'Enemy Hits'
playerstat_enemykills: 'Enemy Kills'
playerstat_enemykillslasthits: 'Enemy Kills Last Hits'
playerstat_playerhits: 'Player Hits'
playerstat_playerkills: 'Player Kills'
playerstat_hitstakenenemies: 'Hits Taken Enemies'
playerstat_hitstakenplayers: 'Hits Taken Players'
playerstat_itemspickedup: 'Items Picked Up'
playerstat_crafts: 'Crafts'
playerstat_upgrades: 'Upgrades'
playerstat_portalsused: 'Portals Used'
playerstat_distancetraveled: 'Distance Traveled'
playerstat_distancewalk: 'Distance Walk'
playerstat_distancerun: 'Distance Run'
playerstat_distancesail: 'Distance Sail'
playerstat_distanceair: 'Distance Air'
playerstat_timeinbase: 'Time In Base'
playerstat_timeoutofbase: 'Time Out Of Base'
playerstat_sleep: 'Sleep'
playerstat_itemstanduses: 'Item Stand Uses'
playerstat_armorstanduses: 'Armor Stand Uses'
playerstat_worldloads: 'World Loads'
playerstat_treechops: 'Tree Chops'
playerstat_tree: 'Tree'
playerstat_treetier0: 'Tree Tier0'
playerstat_treetier1: 'Tree Tier1'
playerstat_treetier2: 'Tree Tier2'
playerstat_treetier3: 'Tree Tier3'
playerstat_treetier4: 'Tree Tier4'
playerstat_treetier5: 'Tree Tier5'
playerstat_logchops: 'Log Chops'
playerstat_logs: 'Logs'
playerstat_minehits: 'Mine Hits'
playerstat_mines: 'Mines'
playerstat_minetier0: 'Mine Tier0'
playerstat_minetier1: 'Mine Tier1'
playerstat_minetier2: 'Mine Tier2'
playerstat_minetier3: 'Mine Tier3'
playerstat_minetier4: 'Mine Tier4'
playerstat_minetier5: 'Mine Tier5'
playerstat_ravenhits: 'Raven Hits'
playerstat_raventalk: 'Raven Talk'
playerstat_ravenappear: 'Raven Appear'
playerstat_creaturetamed: 'Creature Tamed'
playerstat_foodeaten: 'Food Eaten'
playerstat_skeletonsummons: 'Skeleton Summons'
playerstat_arrowsshot: 'Arrows Shot'
playerstat_tombstonesopenedown: 'Tombstones Opened Own'
playerstat_tombstonesopenedother: 'Tombstones Opened Other'
playerstat_tombstonesfit: 'Tombstones Fit'
playerstat_deathbyundefined: 'Death By Undefined'
playerstat_deathbyenemyhit: 'Death By Enemy Hit'
playerstat_deathbyplayerhit: 'Death By Player Hit'
playerstat_deathbyfall: 'Death By Fall'
playerstat_deathbydrowning: 'Death By Drowning'
playerstat_deathbyburning: 'Death By Burning'
playerstat_deathbyfreezing: 'Death By Freezing'
playerstat_deathbypoisoned: 'Death By Poisoned'
playerstat_deathbysmoke: 'Death By Smoke'
playerstat_deathbywater: 'Death By Water'
playerstat_deathbyedgeofworld: 'Death By Edge Of World'
playerstat_deathbyimpact: 'Death By Impact'
playerstat_deathbycart: 'Death By Cart'
playerstat_deathbytree: 'Death By Tree'
playerstat_deathbyself: 'Death By Self'
playerstat_deathbystructural: 'Death By Structural'
playerstat_deathbyturret: 'Death By Turret'
playerstat_deathbyboat: 'Death By Boat'
playerstat_deathbystalagtite: 'Death By Stalagtite'
playerstat_doorsopened: 'Doors Opened'
playerstat_doorsclosed: 'Doors Closed'
playerstat_beesharvested: 'Bees Harvested'
playerstat_sapharvested: 'Sap Harvested'
playerstat_turretammoadded: 'Turret Ammo Added'
playerstat_turrettrophyset: 'Turret Trophy Set'
playerstat_traparmed: 'Trap Armed'
playerstat_traptriggered: 'Trap Triggered'
playerstat_placestacks: 'Place Stacks'
playerstat_portaldungeonin: 'Portal Dungeon In'
playerstat_portaldungeonout: 'Portal Dungeon Out'
playerstat_bosskills: 'Boss Kills'
playerstat_bosslasthits: 'Boss Last Hits'
playerstat_setguardianpower: 'Set Guardian Power'
playerstat_setpowereikthyr: 'Set Power Eikthyr'
playerstat_setpowerelder: 'Set Power Elder'
playerstat_setpowerbonemass: 'Set Power Bonemass'
playerstat_setpowermoder: 'Set Power Moder'
playerstat_setpoweryagluth: 'Set Power Yagluth'
playerstat_setpowerqueen: 'Set Power Queen'
playerstat_setpowerashlands: 'Set Power Ashlands'
playerstat_setpowerdeepnorth: 'Set Power Deep North'
playerstat_useguardianpower: 'Use Guardian Power'
playerstat_usepowereikthyr: 'Use Power Eikthyr'
playerstat_usepowerelder: 'Use Power Elder'
playerstat_usepowerbonemass: 'Use Power Bonemass'
playerstat_usepowermoder: 'Use Power Moder'
playerstat_usepoweryagluth: 'Use Power Yagluth'
playerstat_usepowerqueen: 'Use Power Queen'
playerstat_usepowerashlands: 'Use Power Ashlands'
playerstat_usepowerdeepnorth: 'Use Power Deep North'
playerstat_deathbycatapult: 'Death By Catapult'
playerstat_deathbycinderfire: 'Death By Cinder Fire'
playerstat_deathbyashlandsocean: 'Death By Ashlands Ocean'
playerstat_deathbyincinerator: 'Death By Incinerator'
playerstat_craftfood: 'Craft Food'
playerstat_craftfoodbonus: 'Craft Food Bonus'
playerstat_craftgrill: 'Craft Grill'
playerstat_craftgrillburnt: 'Craft Grill Burnt'
playerstat_craftgrillbonus: 'Craft Grill Bonus'
playerstat_craftweapon: 'Craft Weapon'
playerstat_craftarmor: 'Craft Armor'
playerstat_crafttrinket: 'Craft Trinket'
playerstat_craftammo: 'Craft Ammo'
playerstat_craftmaterial: 'Craft Material'
playerstat_crafttool: 'Craft Tool'
playerstat_crafttorch: 'Craft Torch'
playerstat_craftbait: 'Craft Bait'
playerstat_craftother: 'Craft Other'
playerstat_harvestcrop: 'Harvest Crop'
playerstat_harvestberry: 'Harvest Berry'
playerstat_harvestmushroom: 'Harvest Mushroom'
playerstat_harvestvine: 'Harvest Vine'
playerstat_harvestbonus: 'Harvest Bonus'
playerstat_consecutivedayssurvived: 'Consecutive Days Survived'
playerstat_consecutivedayssurvivedmax: 'Consecutive Days Survived Max'
playerstat_maxbuildingheight: 'Max Building Height'
playerstat_maxbuildingheightworld: 'Max Building Height World'
playerstat_maxcomfort: 'Max Comfort'
playerstat_treasureburiedfound: 'Treasure Buried Found'
playerstat_treasuredungeonfound: 'Treasure Dungeon Found'
playerstat_treasurelocationfound: 'Treasure Location Found'
playerstat_leviathansink: 'Leviathan Sink'
playerstat_lavaleviathansink: 'Lava Leviathan Sink'
playerstat_explorenorth: 'Explore North'
playerstat_exploresouth: 'Explore South'
playerstat_exploreeast: 'Explore East'
playerstat_explorewest: 'Explore West'
playerstat_explorenorthnomap: 'Explore North No Map'
playerstat_exploresouthnomap: 'Explore South No Map'
playerstat_exploreeastnomap: 'Explore East No Map'
playerstat_explorewestnomap: 'Explore West No Map'
playerstat_bosskillmultiplayer: 'Boss Kill Multiplayer'
playerstat_bosskillsolo: 'Boss Kill Solo'
playerstat_villagepointsmax: 'Village Points Max'
playerstat_deepestdungeon: 'Deepest Dungeon'
playerstat_distancesailhelm: 'Distance Sail Helm'
playerstat_playerspawn: 'Player Spawn'
playerstat_deathbytreetier0: 'Death By Tree Tier0'
playerstat_deathbytreetier1: 'Death By Tree Tier1'
playerstat_deathbytreetier2: 'Death By Tree Tier2'
playerstat_deathbytreetier3: 'Death By Tree Tier3'
playerstat_deathbytreetier4: 'Death By Tree Tier4'
playerstat_deathbytreetier5: 'Death By Tree Tier5'
playerstat_fishhooked: 'Fish Hooked'
playerstat_fishlost: 'Fish Lost'
playerstat_fishcaught: 'Fish Caught'
playerstat_fishcaughttier0: 'Fish Caught Tier0'
playerstat_fishcaughttier1: 'Fish Caught Tier1'
playerstat_fishcaughttier2: 'Fish Caught Tier2'
playerstat_fishcaughttier3: 'Fish Caught Tier3'
playerstat_fishcaughttier4: 'Fish Caught Tier4'
playerstat_fishcaughttier5: 'Fish Caught Tier5'
playerstat_fishcaughttier6: 'Fish Caught Tier6'
playerstat_builtpieces: 'Built Pieces'
playerstat_builtpiecesnodebt: 'Built Pieces No Debt'
playerstat_buildpiecesremoved: 'Build Pieces Removed'
playerstat_buildclustermisc: 'Build Cluster Misc'
playerstat_buildclustercrafting: 'Build Cluster Crafting'
playerstat_buildclusterbuilding: 'Build Cluster Building'
playerstat_buildclusterfloor: 'Build Cluster Floor'
playerstat_buildclusterwall: 'Build Cluster Wall'
playerstat_buildclusterroof: 'Build Cluster Roof'
playerstat_buildclusterarchitecture: 'Build Cluster Architecture'
playerstat_buildclusterfurniture: 'Build Cluster Furniture'
playerstat_buildclusterlighting: 'Build Cluster Lighting'
playerstat_buildclusterdecor: 'Build Cluster Decor'
playerstat_buildclusterstorage: 'Build Cluster Storage'
playerstat_buildclustertransport: 'Build Cluster Transport'
playerstat_buildclusterfood: 'Build Cluster Food'
playerstat_buildclustermeads: 'Build Cluster Meads'
playerstat_buildclusterfeasts: 'Build Cluster Feasts'
playerstat_buildclusterdefense: 'Build Cluster Defense'
playerstat_buildclusterstacks: 'Build Cluster Stacks'
playerstat_buildclusterstairs: 'Build Cluster Stairs'
playerstat_buildclusterdoors: 'Build Cluster Doors'
playerstat_buildclusterseasonal: 'Build Cluster Seasonal'
playerstat_tamedpetting: 'Tamed Petting'
playerstat_tamedcommand: 'Tamed Command'
playerstat_treefir: 'Tree Fir'
playerstat_treeoak: 'Tree Oak'
playerstat_treepine: 'Tree Pine'
playerstat_treeashlands: 'Tree Ashlands'
playerstat_treeyggdrasilshoot: 'Tree Yggdrasil Shoot'
playerstat_treeswamp: 'Tree Swamp'
playerstat_treebeech: 'Tree Beech'
playerstat_treebirch: 'Tree Birch'
playerstat_treesnowfir: 'Tree Snow Fir'
playerstat_treesnowpine: 'Tree Snow Pine'
playerstat_deathbydrawbridge: 'Death By Draw Bridge'
playerstat_deathbyashlandslava: 'Death By Ashlands Lava'
playerstat_count: 'Count'
playerstat_none: 'None'
label_none: 'None'
label_deaths: 'Deaths'
label_weapons: 'Weapons'
label_swords: 'Swords'
label_axes: 'Axes'
label_polearms: 'Pole Arms'
label_spears: 'Spears'
label_maces: 'Maces'
label_knives: 'Knives'
label_shields: 'Shields'
label_arrows: 'Arrows'
label_bows: 'Bows'
label_trophies: 'Trophies'
label_enemykills: 'Enemy Kills'
label_treeschopped: 'Trees Chopped'
label_timeinbase: 'Time In Base'
label_timeoutofbase: 'Time Out Of Base'
label_arrowsshot: 'Arrows Shot'
label_totaljumps: 'Total Jumps'
label_playerkills: 'Player Kills'
label_itemspicked: 'Items Picked'
label_distancewalked: 'Distance Walked'
label_distanceran: 'Distance Ran'
label_distancesailed: 'Distance Sailed'
label_distanceinair: 'Distance In Air'
label_minehits: 'Mine Hits'
label_totalmined: 'Total Mined'
label_creaturetamed: 'Creature Tamed'
label_foodeaten: 'Food Eaten'
label_creaturegroup: 'Creature Group'
label_pickable: 'Pickable'
label_kill: 'Kill'
label_collectitems: 'Collect Items'
label_achievements: 'Achievements'
faction_players: 'Players'
faction_animalsveg: 'Animals Veg'
faction_forestmonsters: 'Forest Monsters'
faction_undead: 'Undead'
faction_demon: 'Demon'
faction_mountainmonsters: 'Mountain Monsters'
faction_seamonsters: 'Sea Monsters'
faction_plainsmonsters: 'Plains Monsters'
faction_boss: 'Boss'
faction_mistlandsmonsters: 'Mistlands Monsters'
faction_dverger: 'Dverger'
faction_playerspawned: 'Player Spawned'
faction_trainingdummy: 'Training Dummy'
faction_deepnorth: 'Deep North'
